var customers = 
[
 {
  "Result":"passed",
  "Test":"My first test 1",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 284ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 2",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 434ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 3",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 419ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 4",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"850ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 5",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"840ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 6",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"875ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 7",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"836ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 8",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"853ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 9",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"883ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 10",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"874ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test screenshot",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 616ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My first test 1s",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 543ms",
  "Report":"",
 },
 {
  "Result":"skipped",
  "Test":"My first skip",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"970ms",
  "Report":"",
 },
 {
  "Result":"failed",
  "Test":"My first error",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"4s 409ms",
  "Report":"<pre>\
AssertionError: expected 'Thank you, John Smith!' to deeply equal 'Thank you, John Smith2!'\n\
\n\
Browser: HeadlessChrome 67.0.3371 / Windows 7.0.0\n\
\n\
   114 |  await t\n\
   115 |    .typeText('#developer-name', 'John Smith')\n\
   116 |    .click('#submit-button')\n\
   117 |\n\
   118 |    // Use the assertion to check if the actual header text is equal to the expected one\n\
 > 119 |    .expect(Selector('#article-header').innerText).eql('Thank you, John Smith2!');\n\
   120 |});\n\
   121 |\n\
   122 |test('My first warning', async t => {\n\
   123 |  await t\n\
   124 |    .maximizeWindow();\n\
\n\
   at <anonymous> (D:\\nodejs\\npm\\node_modules\\testcafe-reporter-st-dx\\test\\fixture1.js:119:52)\n\
   at test (D:\\nodejs\\npm\\node_modules\\testcafe-reporter-st-dx\\test\\fixture1.js:113:1)\
</pre>\
",
 },
 {
  "Result":"passed",
  "Test":"My first warning",
  "Fixture":"Getting Started",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"3s 694ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 1",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"3s 443ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 2",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"2s 779ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 3",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"2s 619ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 4",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 969ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 5",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 806ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 6",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 140ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 7",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"976ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 8",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"810ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 9",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"849ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My second test 10",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"844ms",
  "Report":"",
 },
 {
  "Result":"skipped",
  "Test":"My second skip",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"358ms",
  "Report":"",
 },
 {
  "Result":"failed",
  "Test":"My second error",
  "Fixture":"Getting second",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"4s 317ms",
  "Report":"<pre>\
AssertionError: expected 'Thank you, John Smith!' to deeply equal 'Thank you, John Smith2!'\n\
\n\
Browser: HeadlessChrome 67.0.3371 / Windows 7.0.0\n\
\n\
   106 |  await t\n\
   107 |    .typeText('#developer-name', 'John Smith')\n\
   108 |    .click('#submit-button')\n\
   109 |\n\
   110 |    // Use the assertion to check if the actual header text is equal to the expected one\n\
 > 111 |    .expect(Selector('#article-header').innerText).eql('Thank you, John Smith2!');\n\
   112 |});\n\
   113 |\n\
\n\
   at <anonymous> (D:\\nodejs\\npm\\node_modules\\testcafe-reporter-st-dx\\test\\fixture2.js:111:52)\n\
   at test (D:\\nodejs\\npm\\node_modules\\testcafe-reporter-st-dx\\test\\fixture2.js:105:1)\
</pre>\
",
 },
 {
  "Result":"passed",
  "Test":"My first test 1",
  "Fixture":"Getting third",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"4s 103ms",
  "Report":"",
 },
 {
  "Result":"skipped",
  "Test":"My first skip",
  "Fixture":"Getting third",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"3s 959ms",
  "Report":"",
 },
 {
  "Result":"failed",
  "Test":"My first error",
  "Fixture":"Getting third",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"4s 255ms",
  "Report":"<pre>\
AssertionError: expected 'Thank you, John Smith!' to deeply equal 'Thank you, John Smith2!'\n\
\n\
Browser: HeadlessChrome 67.0.3371 / Windows 7.0.0\n\
\n\
   25 |  await t\n\
   26 |    .typeText('#developer-name', 'John Smith')\n\
   27 |    .click('#submit-button')\n\
   28 |\n\
   29 |    // Use the assertion to check if the actual header text is equal to the expected one\n\
 > 30 |    .expect(Selector('#article-header').innerText).eql('Thank you, John Smith2!');\n\
   31 |});\n\
   32 |\n\
   33 |test.skip('My first skip2', async t => {\n\
   34 |  await t\n\
   35 |    .typeText('#developer-name', 'John Smith')\n\
\n\
   at <anonymous> (D:\\nodejs\\npm\\node_modules\\testcafe-reporter-st-dx\\test\\fixture3.js:30:52)\n\
   at test (D:\\nodejs\\npm\\node_modules\\testcafe-reporter-st-dx\\test\\fixture3.js:24:1)\
</pre>\
",
 },
 {
  "Result":"skipped",
  "Test":"My first skip2",
  "Fixture":"Getting third",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"3s 579ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 1",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"3s 578ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 2",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"2s 713ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 3",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 918ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 4",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"1s 063ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 5",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"812ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 6",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"828ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 7",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"881ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 8",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"845ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 9",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"832ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 10",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"850ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 11",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"881ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 12",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"879ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 13",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"858ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 14",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"841ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 15",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"834ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 16",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"828ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 17",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"838ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 18",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"847ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 19",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"837ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 20",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"839ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 21",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"858ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 22",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"865ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 23",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"858ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 24",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"820ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 25",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"864ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 26",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"827ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 27",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"865ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 28",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"815ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 29",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"825ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 30",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"829ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 31",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"858ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 32",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"864ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 33",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"841ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 34",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"844ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 35",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"832ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 36",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"838ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 37",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"829ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 38",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"833ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 39",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"843ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 40",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"857ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 41",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"844ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 42",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"841ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 43",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"828ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 44",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"831ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 45",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"839ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 46",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"827ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 47",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"839ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 48",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"856ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 49",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"867ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 50",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"835ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 51",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"860ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 52",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"819ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 53",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"825ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 54",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"828ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 55",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"836ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 56",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"860ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 57",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"868ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 58",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"864ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 59",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"844ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 60",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"833ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 61",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"834ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 62",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"845ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 63",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"873ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 64",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"851ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 65",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"818ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 66",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"813ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 67",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"824ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 68",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"823ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 69",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"865ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 70",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"867ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 71",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"832ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 72",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"844ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 73",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"838ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 74",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"818ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 75",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"837ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 76",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"892ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 77",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"861ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 78",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"886ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 79",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"818ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 80",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"824ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 81",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"851ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 82",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"844ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 83",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"836ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 84",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"826ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 85",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"872ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 86",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"865ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 87",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"857ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 88",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"828ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 89",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"822ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 90",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"835ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 91",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"845ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 92",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"845ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 93",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"890ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 94",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"835ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 95",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"843ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 96",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"825ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 97",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"850ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 98",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"814ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 99",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"856ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 100",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"865ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 101",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"862ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 102",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"831ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 103",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"888ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 104",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"837ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 105",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"824ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 106",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"842ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 107",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"863ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 108",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"839ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 109",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"858ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 110",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"819ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 111",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"840ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 112",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"915ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 113",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"880ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 114",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"881ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 115",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"862ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 116",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"830ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 117",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"826ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 118",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"826ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 119",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"863ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 120",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"826ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 121",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"842ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 122",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"827ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 123",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"845ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 124",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"827ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 125",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"833ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 126",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"826ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 127",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"828ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 128",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"840ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 129",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"824ms",
  "Report":"",
 },
 {
  "Result":"passed",
  "Test":"My fourth test 130",
  "Fixture":"Getting fourth",
  "Browser":"HeadlessChrome 67.0.3371 / Windows 7.0.0",
  "Duration":"819ms",
  "Report":"",
 },

];